CREATE TABLE projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE project_users (
    project_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, user_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Note: In a production heavily-populated environment, adding a foreign key with NOT NULL 
-- requires default values or a multi-step migration. Since the DB is mostly empty,
-- we will just add the column, set it to a default '1', and then make it NOT NULL and add FK constraint.
-- Actually, there might not be a project '1' yet. We should create a default project first.

INSERT INTO projects (id, name, description) VALUES (1, 'Default Project', 'Autogenerated default project');

ALTER TABLE strings DROP COLUMN project_id;
ALTER TABLE strings ADD COLUMN project_id INT NOT NULL DEFAULT 1 AFTER id;
ALTER TABLE strings ADD CONSTRAINT fk_string_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE glossary_terms ADD COLUMN project_id INT NOT NULL DEFAULT 1 AFTER id;
ALTER TABLE glossary_terms ADD CONSTRAINT fk_glossary_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

-- Also seed the admin to the default project just in case, though admins will bypass this in logic
INSERT INTO project_users (project_id, user_id) 
SELECT 1, id FROM users WHERE role = 'admin';
